#!/bin/bash
clear
echo "------------------------------------------------------------------------------"
if [ "$1" == "" ]; then
	echo "  Nothing to search for!"
else
	echo "  Searching for "$1" recursively. Please Wait..."
	echo "------------------------------------------------------------------------------"
	grep -h -r --exclude=B00 -H --colour=always "$1" ./
fi
echo "------------------------------------------------------------------------------"
if [ "$2" != "" ]; then
	echo "  To replace \"$1\" whith \"$2\", please run"
	echo "  grep -rl '$1' ./  | xargs sed -i 's~$1~$2~g'"
fi
## THIS IS A GREAT RETRO ENGINEERING AND CODING TOOLS
