#!/bin/bash
MY_PATH="`dirname \"$0\"`"              # relative
MY_PATH="`( cd \"$MY_PATH\" && pwd )`"  # absolutized and normalized
ME="${0##*/}"
## THIS IS A GREAT RETRO ENGINEERING AND CODE SNIFFING TOOLS
clear
[[ ! -s ~/.local/bin/${ME} ]] && cp ${MY_PATH}/${ME} ~/.local/bin/ && echo "Auto Install into ~/.local/bin/${ME}"
echo "------------------------------------------------------------------------------"
if [ "$1" == "" ]; then
    echo "  Nothing to search for!"
else
    echo "  Searching for "$1" recursively. Please Wait..."
    echo "------------------------------------------------------------------------------"
    grep -h -r --exclude-dir='.git*' --exclude='twuplanet.html' --exclude='twsector.html' -H --colour=always "$1" ./
fi
echo "------------------------------------------------------------------------------"
if [ "$2" != "" ]; then
    echo "  To replace \"$1\" whith \"$2\", please run"
    echo "  grep -rl --exclude-dir='.git*' --exclude='twuplanet.html' --exclude='twsector.html' '$1' ./  | xargs sed -i 's~$1~$2~g'"
fi
exit 0
