#!/bin/bash
########################################################################
# astroport.sh — Docker entrypoint for Astroport.ONE
# Handles: code update, runtime setup (idempotent), service launch
########################################################################
set -euo pipefail
[ -n "${DEBUG:-}" ] && set -x

ASTRO="$HOME/.zen/Astroport.ONE"
ASTRO_REPO="https://github.com/papiche/Astroport.ONE.git"

########################################################################
## Update or clone Astroport.ONE code
########################################################################
update_code() {
    if [ -d "$ASTRO/.git" ]; then
        echo ">>> Updating Astroport.ONE code..."
        cd "$ASTRO" && git pull -q --recurse-submodules
    else
        echo ">>> Cloning Astroport.ONE..."
        git clone --recurse-submodules --depth 1 "$ASTRO_REPO" "$ASTRO"
    fi
}

########################################################################
## Runtime setup (idempotent — safe to run on every start)
########################################################################
runtime_setup() {
    echo ">>> Runtime setup..."

    ## Activate python venv
    [ -s "$HOME/.astro/bin/activate" ] && . "$HOME/.astro/bin/activate"

    ## IPFS init (only if no repo exists)
    if [ ! -d "$HOME/.ipfs" ]; then
        echo ">>> Initializing IPFS..."
        ipfs init --profile server
    fi
    echo "/ip4/127.0.0.1/tcp/5001" > "$HOME/.ipfs/api"

    ## Generate NODE wallet from IPFS identity (Docker equivalent of Ylevel.sh)
    ## In Docker there is no SSH key, so we derive NODE dunikey directly from
    ## the IPFS node private key (same crypto: ed25519 protobuf → duniter)
    if [ ! -s "$HOME/.zen/game/secret.NODE.dunikey" ]; then
        echo ">>> Generating NODE wallet from IPFS identity..."
        mkdir -p "$HOME/.zen/tmp" "$HOME/.zen/game"
        ## Extract IPFS private key (base64 protobuf) to binary file
        ## Non-fatal: NODE wallet is important but not a blocker
        if python3 -c "
import json, base64, sys
cfg = json.load(open('$HOME/.ipfs/config'))
sys.stdout.buffer.write(base64.b64decode(cfg['Identity']['PrivKey']))
" > "$HOME/.zen/tmp/ipfs_node.pb2" 2>/dev/null && [ -s "$HOME/.zen/tmp/ipfs_node.pb2" ]; then
            "$ASTRO/tools/keygen" -i "$HOME/.zen/tmp/ipfs_node.pb2" -t duniter \
                -o "$HOME/.zen/game/secret.NODE.dunikey" 2>/dev/null \
                && chmod 600 "$HOME/.zen/game/secret.NODE.dunikey" \
                && echo ">>> NODE wallet created (from IPFS identity)" \
                || echo ">>> WARNING: NODE wallet keygen failed"
        else
            echo ">>> WARNING: could not extract IPFS private key for NODE wallet"
        fi
        rm -f "$HOME/.zen/tmp/ipfs_node.pb2"
    fi

    ## Install IPFS swarm.key (private network)
    ## IPFS_SWARM_KEY env var overrides — otherwise default ORIGIN key (000...0)
    if [ -n "${IPFS_SWARM_KEY:-}" ]; then
        echo ">>> Installing custom IPFS swarm.key (UPlanet ẐEN)"
        cat > "$HOME/.ipfs/swarm.key" <<SWARMKEY
/key/swarm/psk/1.0.0/
/base16/
${IPFS_SWARM_KEY}
SWARMKEY
    elif [ ! -s "$HOME/.ipfs/swarm.key" ]; then
        echo ">>> Installing default IPFS swarm.key (UPlanet ORIGIN)"
        cat > "$HOME/.ipfs/swarm.key" <<SWARMKEY
/key/swarm/psk/1.0.0/
/base16/
0000000000000000000000000000000000000000000000000000000000000000
SWARMKEY
    fi
    chmod 600 "$HOME/.ipfs/swarm.key"

    ## Generate .env if missing
    if [ ! -s "$ASTRO/.env" ]; then
        SETUP_DOMAIN="${ASTRO_DOMAIN:-copylaradio.com}"
        cat > "$ASTRO/.env" <<DOTENV
#########################################
# ASTROPORT box - Auto-generated by Docker entrypoint
# Domain: ${SETUP_DOMAIN}
# Date: $(date -Is)
#########################################
myASTROPORT=https://astroport.${SETUP_DOMAIN}
myIPFS=https://ipfs.${SETUP_DOMAIN}
myRELAY=wss://relay.${SETUP_DOMAIN}
uSPOT=https://u.${SETUP_DOMAIN}

###################################
## ZEN ECONOMY (configurable via docker env)
###################################
MACHINE_VALUE_ZEN=${MACHINE_VALUE_ZEN:-500}
PAF=${PAF:-14}
NCARD=${NCARD:-1}
ZCARD=${ZCARD:-4}
LOG_LEVEL=INFO
ENABLE_AUDIO_NOTIFICATIONS=no
DOTENV
        echo ">>> .env created for domain: ${SETUP_DOMAIN}"
        echo ">>> Economy: MACHINE=${MACHINE_VALUE_ZEN:-500} PAF=${PAF:-14} NCARD=${NCARD:-1} ZCARD=${ZCARD:-4}"
    fi

    ## Source environment
    . "$ASTRO/tools/my.sh"

    ## Ensure directories
    mkdir -p "$HOME/.zen/tmp" "$HOME/.zen/game/players" "$HOME/.zen/game/nostr"

    ## Captain onboarding (only once — skipped if captain already exists)
    if [ ! -d "$HOME/.zen/game/players/.current" ]; then
        echo ">>> First run: creating captain account..."
        GO=$(my_LatLon 2>/dev/null || echo "FR 48.86 2.35")

        ## Use CAPTAIN_EMAIL env var if provided, otherwise auto-generate
        if [ -n "${CAPTAIN_EMAIL:-}" ]; then
            GMARKMAIL="${CAPTAIN_EMAIL}"
            echo ">>> Captain email from env: ${GMARKMAIL}"
        else
            GMARKMAIL="support+$(echo "$(hostname) $GO" | sed 's| |_|g')@qo-op.com"
            echo ">>> Captain email auto-generated: ${GMARKMAIL}"
        fi

        ## MULTIPASS
        "$ASTRO/tools/make_NOSTRCARD.sh" "${GMARKMAIL}" $GO || true

        ## ZENCARD
        ZSALT=$("$ASTRO/tools/diceware.sh" $(( $("$ASTRO/tools/getcoins_from_gratitude_box.sh" 2>/dev/null || echo 0) + 3 )))
        ZPEPS=$("$ASTRO/tools/diceware.sh" $(( $("$ASTRO/tools/getcoins_from_gratitude_box.sh" 2>/dev/null || echo 0) + 3 )))

        if [ -s "$HOME/.zen/game/nostr/${GMARKMAIL}/.secret.nostr" ]; then
            . "$HOME/.zen/game/nostr/${GMARKMAIL}/.secret.nostr"
            "$ASTRO/RUNTIME/VISA.new.sh" "$ZSALT" "$ZPEPS" "${GMARKMAIL}" "UPlanet" $GO "$NPUB" "$HEX" || true
        fi
        echo ">>> Captain onboarded: ${GMARKMAIL}"
    else
        echo ">>> Captain already onboard: $(cat "$HOME/.zen/game/players/.current/.player" 2>/dev/null)"
    fi

    ## Initialize cooperative wallets (primo TX from UPLANETNAME_G1)
    ## Idempotent: skips wallets already funded, non-blocking if source has 0 balance
    echo ">>> Cooperative wallet initialization..."
    "$ASTRO/UPLANET.init.sh" --force || echo ">>> UPLANET.init: wallets created, fund uplanet.G1.dunikey to finalize"
}

########################################################################
## Start services
########################################################################
start_services() {
    echo ">>> Starting IPFS daemon..."
    ipfs daemon --enable-pubsub-experiment &
    sleep 3

    echo ">>> Starting Astroport API (12345.sh)..."
    exec "$ASTRO/12345.sh"
}

########################################################################
## Main
########################################################################
case "${1:-start}" in
    start)
        update_code
        runtime_setup
        start_services
        ;;
    setup)
        update_code
        runtime_setup
        echo ">>> Setup complete (no services started)"
        ;;
    *)
        exec "$@"
        ;;
esac
