#!/bin/bash
########################################################################
# astroport-desktop.sh — Docker entrypoint for Astroport.ONE Desktop VDI
#
# Handles: VNC/noVNC startup, UPlanet network selection (ORIGIN/ZEN),
#          first-boot install.sh, Astroport services, desktop shortcuts
# Access: http://localhost:6080 (noVNC in browser)
########################################################################
set -euo pipefail
[ -n "${DEBUG:-}" ] && set -x

ASTRO="$HOME/.zen/Astroport.ONE"
VNC_DISPLAY="${VNC_DISPLAY:-:1}"
VNC_PORT="${VNC_PORT:-5901}"
NOVNC_PORT="${NOVNC_PORT:-6080}"
VNC_RESOLUTION="${VNC_RESOLUTION:-1280x720}"
VNC_DEPTH="${VNC_DEPTH:-24}"
VNC_PASSWORD="${VNC_PASSWORD:-astroport}"

########################################################################
## Run as zen user (if started as root, re-exec as zen)
########################################################################
if [ "$(id -u)" = "0" ]; then
    # Ensure home ownership (volumes may be root-owned on first run)
    chown -R "${USER}:${USER}" "$HOME" 2>/dev/null || true
    exec su - "${USER}" -c "VNC_PASSWORD='${VNC_PASSWORD}' \
        VNC_RESOLUTION='${VNC_RESOLUTION}' \
        ASTRO_DOMAIN='${ASTRO_DOMAIN:-copylaradio.com}' \
        CAPTAIN_EMAIL='${CAPTAIN_EMAIL:-}' \
        IPFS_SWARM_KEY='${IPFS_SWARM_KEY:-}' \
        MACHINE_VALUE_ZEN='${MACHINE_VALUE_ZEN:-500}' \
        PAF='${PAF:-14}' NCARD='${NCARD:-1}' ZCARD='${ZCARD:-4}' \
        DEBUG='${DEBUG:-}' \
        /app/astroport-desktop.sh"
fi

########################################################################
## 1. VNC SERVER
########################################################################
start_vnc() {
    echo ">>> Configuring VNC..."
    mkdir -p "$HOME/.vnc"

    # Set VNC password
    echo "$VNC_PASSWORD" | vncpasswd -f > "$HOME/.vnc/passwd"
    chmod 600 "$HOME/.vnc/passwd"

    # XFCE session startup
    cat > "$HOME/.vnc/xstartup" <<'XSTARTUP'
#!/bin/bash
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS
export XDG_SESSION_TYPE=x11
exec startxfce4
XSTARTUP
    chmod +x "$HOME/.vnc/xstartup"

    echo ">>> Starting TigerVNC on ${VNC_DISPLAY} (${VNC_RESOLUTION})..."
    vncserver "${VNC_DISPLAY}" \
        -geometry "$VNC_RESOLUTION" \
        -depth "$VNC_DEPTH" \
        -localhost yes \
        -SecurityTypes VncAuth &

    # Wait for X server
    for i in $(seq 1 30); do
        [ -e "/tmp/.X11-unix/X${VNC_DISPLAY#:}" ] && break
        sleep 1
    done
    export DISPLAY="${VNC_DISPLAY}"
    echo ">>> VNC server ready"
}

########################################################################
## 2. noVNC PROXY (WebSocket → VNC)
########################################################################
start_novnc() {
    echo ">>> Starting noVNC on port ${NOVNC_PORT}..."
    websockify \
        --web /usr/share/novnc \
        "${NOVNC_PORT}" \
        "localhost:${VNC_PORT}" &
    NOVNC_PID=$!
}

########################################################################
## 3. UPLANET NETWORK CONFIGURATION (ORIGIN or ZEN)
########################################################################
configure_uplanet() {
    local SETUP_DOMAIN="${ASTRO_DOMAIN:-copylaradio.com}"

    ## IPFS swarm.key — determines which UPlanet network this station joins
    ## IPFS_SWARM_KEY="" or unset → UPlanet ORIGIN (open sandbox, 1 Zen = 0.1 G1)
    ## IPFS_SWARM_KEY=<64hex>   → UPlanet ZEN (cooperative network, 1 Zen = 1 EUR)
    if [ -n "${IPFS_SWARM_KEY:-}" ]; then
        echo ">>> UPlanet ZEN — installing swarm.key for domain: ${SETUP_DOMAIN}"
        mkdir -p "$HOME/.ipfs"
        cat > "$HOME/.ipfs/swarm.key" <<SWARMKEY
/key/swarm/psk/1.0.0/
/base16/
${IPFS_SWARM_KEY}
SWARMKEY
        chmod 600 "$HOME/.ipfs/swarm.key"
    else
        echo ">>> UPlanet ORIGIN — open sandbox network"
        if [ -d "$HOME/.ipfs" ] && [ ! -s "$HOME/.ipfs/swarm.key" ]; then
            cat > "$HOME/.ipfs/swarm.key" <<SWARMKEY
/key/swarm/psk/1.0.0/
/base16/
0000000000000000000000000000000000000000000000000000000000000000
SWARMKEY
            chmod 600 "$HOME/.ipfs/swarm.key"
        fi
    fi

    ## Generate Astroport .env (domain-specific endpoints)
    if [ ! -s "$ASTRO/.env" ]; then
        echo ">>> Generating .env for domain: ${SETUP_DOMAIN}"
        cat > "$ASTRO/.env" <<DOTENV
#########################################
# ASTROPORT box - Auto-generated by Desktop VDI entrypoint
# Domain: ${SETUP_DOMAIN}
# Network: $([ -n "${IPFS_SWARM_KEY:-}" ] && echo "UPlanet ZEN" || echo "UPlanet ORIGIN")
# Date: $(date -Is)
#########################################
myASTROPORT=https://astroport.${SETUP_DOMAIN}
myIPFS=https://ipfs.${SETUP_DOMAIN}
myRELAY=wss://relay.${SETUP_DOMAIN}
uSPOT=https://u.${SETUP_DOMAIN}

###################################
## ZEN ECONOMY (configurable via docker env)
###################################
MACHINE_VALUE_ZEN=${MACHINE_VALUE_ZEN:-500}
PAF=${PAF:-14}
NCARD=${NCARD:-1}
ZCARD=${ZCARD:-4}
LOG_LEVEL=INFO
ENABLE_AUDIO_NOTIFICATIONS=no
DOTENV
        echo ">>> Economy: MACHINE=${MACHINE_VALUE_ZEN:-500} PAF=${PAF:-14} NCARD=${NCARD:-1} ZCARD=${ZCARD:-4}"
    fi
}

########################################################################
## 4. FIRST-BOOT INSTALL (runs install.sh once)
########################################################################
first_boot_install() {
    local INSTALL_MARKER="$HOME/.zen/.desktop-installed"

    if [ -f "$INSTALL_MARKER" ]; then
        echo ">>> Astroport already installed, skipping install.sh"
        # Still update code
        if [ -d "$ASTRO/.git" ]; then
            cd "$ASTRO" && git pull -q --recurse-submodules || true
        fi
        return 0
    fi

    echo "============================================"
    echo "  FIRST BOOT — Running Astroport install.sh"
    echo "  This takes 10-30 minutes..."
    echo "============================================"

    # Update code
    if [ -d "$ASTRO/.git" ]; then
        cd "$ASTRO" && git pull -q --recurse-submodules || true
    fi

    # Run install.sh (handles all dependencies, IPFS, Python, etc.)
    cd "$ASTRO"
    bash ./install.sh 2>&1 | tee "$HOME/.zen/tmp/install-desktop.log" || {
        echo ">>> WARNING: install.sh had errors (expected for systemd in Docker)"
        echo ">>> Check ~/.zen/tmp/install-desktop.log"
    }

    # Mark as installed
    date -Is > "$INSTALL_MARKER"
    echo ">>> First boot install complete."
}

########################################################################
## 5. ASTROPORT SERVICES
########################################################################
start_astroport() {
    # Activate Python venv
    [ -s "$HOME/.astro/bin/activate" ] && . "$HOME/.astro/bin/activate"

    # Source environment
    [ -s "$ASTRO/tools/my.sh" ] && . "$ASTRO/tools/my.sh" 2>/dev/null || true

    # IPFS daemon
    if command -v ipfs &>/dev/null && [ -d "$HOME/.ipfs" ]; then
        echo ">>> Starting IPFS daemon..."
        ipfs daemon --enable-pubsub-experiment &
        sleep 3
    fi

    # Astroport API
    if [ -x "$ASTRO/12345.sh" ]; then
        echo ">>> Starting Astroport API (12345.sh)..."
        "$ASTRO/12345.sh" &
    fi

    # UPassport
    if [ -d "$HOME/.zen/UPassport" ]; then
        echo ">>> Starting UPassport..."
        (cd "$HOME/.zen/UPassport" && . "$HOME/.astro/bin/activate" && python app.py &) 2>/dev/null || true
    fi
}

########################################################################
## 6. DESKTOP SHORTCUTS
########################################################################
setup_desktop() {
    local DESKTOP_DIR="$HOME/Desktop"
    mkdir -p "$DESKTOP_DIR"

    local SETUP_DOMAIN="${ASTRO_DOMAIN:-copylaradio.com}"
    local NETWORK_LABEL
    if [ -n "${IPFS_SWARM_KEY:-}" ]; then
        NETWORK_LABEL="ZEN (${SETUP_DOMAIN})"
    else
        NETWORK_LABEL="ORIGIN"
    fi

    ## --- Ajouter Media (main user tool) ---
    cat > "$DESKTOP_DIR/AjouterMedia.desktop" <<SHORTCUT
[Desktop Entry]
Type=Application
Name=Ajouter Media
Comment=Ajouter des fichiers, videos, PDF à UPlanet
Icon=${ASTRO}/rec.png
Exec=bash -c 'export DISPLAY=${VNC_DISPLAY}; ${ASTRO}/ajouter_media.sh'
Terminal=false
Categories=Utility;AudioVideo;
SHORTCUT
    chmod +x "$DESKTOP_DIR/AjouterMedia.desktop"

    ## --- Terminal ---
    cat > "$DESKTOP_DIR/Terminal.desktop" <<'SHORTCUT'
[Desktop Entry]
Type=Application
Name=Terminal
Icon=utilities-terminal
Exec=xfce4-terminal
SHORTCUT
    chmod +x "$DESKTOP_DIR/Terminal.desktop"

    ## --- Astroport Dashboard ---
    cat > "$DESKTOP_DIR/Astroport.desktop" <<SHORTCUT
[Desktop Entry]
Type=Application
Name=Astroport Station
Comment=Station Map & API — UPlanet ${NETWORK_LABEL}
Icon=network-server
Exec=firefox-esr http://localhost:12345
SHORTCUT
    chmod +x "$DESKTOP_DIR/Astroport.desktop"

    ## --- UPassport ---
    cat > "$DESKTOP_DIR/UPassport.desktop" <<SHORTCUT
[Desktop Entry]
Type=Application
Name=UPassport
Comment=Identite souveraine — UPlanet ${NETWORK_LABEL}
Icon=preferences-system-privacy
Exec=firefox-esr http://localhost:54321
SHORTCUT
    chmod +x "$DESKTOP_DIR/UPassport.desktop"

    ## --- Files (.zen) ---
    cat > "$DESKTOP_DIR/Files.desktop" <<'SHORTCUT'
[Desktop Entry]
Type=Application
Name=Files (.zen)
Icon=system-file-manager
Exec=thunar /home/zen/.zen
SHORTCUT
    chmod +x "$DESKTOP_DIR/Files.desktop"

    ## --- IPFS WebUI ---
    cat > "$DESKTOP_DIR/IPFS.desktop" <<'SHORTCUT'
[Desktop Entry]
Type=Application
Name=IPFS WebUI
Comment=InterPlanetary File System
Icon=network-transmit-receive
Exec=firefox-esr http://localhost:5001/webui
SHORTCUT
    chmod +x "$DESKTOP_DIR/IPFS.desktop"

    ## --- Network info file on desktop ---
    cat > "$DESKTOP_DIR/UPLANET_NETWORK.txt" <<NETINFO
UPlanet Network: ${NETWORK_LABEL}
Domain: ${SETUP_DOMAIN}
IPFS Gateway: https://ipfs.${SETUP_DOMAIN}
NOSTR Relay: wss://relay.${SETUP_DOMAIN}
UPassport: https://u.${SETUP_DOMAIN}

Swarm: $([ -n "${IPFS_SWARM_KEY:-}" ] && echo "Private (ZEN cooperative)" || echo "Public (ORIGIN sandbox)")

To switch network, restart with:
  IPFS_SWARM_KEY=<64-char-hex> docker compose -f docker-compose.desktop.yml up -d
NETINFO
}

########################################################################
## 7. SIGNAL HANDLING
########################################################################
cleanup() {
    echo ">>> Shutting down desktop VDI..."
    vncserver -kill "${VNC_DISPLAY}" 2>/dev/null || true
    kill "$NOVNC_PID" 2>/dev/null || true
    exit 0
}
trap cleanup SIGTERM SIGINT

########################################################################
## MAIN
########################################################################
start_vnc
start_novnc
configure_uplanet
setup_desktop
first_boot_install
start_astroport

NETWORK_MODE="ORIGIN (sandbox)"
[ -n "${IPFS_SWARM_KEY:-}" ] && NETWORK_MODE="ZEN (${ASTRO_DOMAIN:-copylaradio.com})"

echo ""
echo "=========================================="
echo "  Astroport Desktop VDI Ready"
echo ""
echo "  noVNC:    http://localhost:${NOVNC_PORT}"
echo "  Password: ${VNC_PASSWORD}"
echo "  Station:  http://localhost:12345"
echo "  UPlanet:  ${NETWORK_MODE}"
echo "=========================================="
echo ""

# Keep container alive
wait $NOVNC_PID
