COMPOSE_FILE_VDI                          := true
COMPOSE_IGNORE_ORPHANS                    := true
DOCKER_IMAGES_MYOS                        := x2go:xfce-debian
ENV_VARS                                  += HOST_ASTROPORT_SERVICE_DOMAIN HOST_ASTROPORT_SERVICE_NAME HOST_ASTROPORT_SERVICE_1234_TAGS
HOST_ASTROPORT_SERVICE_DOMAIN             ?= $(firstword $(DOMAIN))
HOST_ASTROPORT_SERVICE_NAME               ?= astroport
HOST_ASTROPORT_SERVICE_1234_TAGS          ?= $(call tagprefix,HOST_ASTROPORT,1234)
HOST_ASTROPORT_UFW_UPDATE                 := 1234/tcp 12245:12445/tcp 45720/tcp
MAKE_VARS                                 += SSH_PORT User host
SERVICE                                   := astroport
SSH_PORT                                  := 45720
SSH_PUBLIC_HOSTS                          := git.p2p.legal
STACK                                     := host
User                                      := User/ipfs
host                                      := host/ipfs
