#!/bin/bash
################################################################ admin/system/station-info.sh
# Affiche les portefeuilles coopératifs et l'état de la station
# Symlink : ~/.local/bin/station-info
################################################################
MY_PATH="$(cd "$(dirname "$(readlink -f "$0")")" && pwd)"

. "${MY_PATH}/../../tools/my.sh" 2>/dev/null

echo "══════════════════════════════════════════════════════════════════════"
echo "🏦 PORTEFEUILLES COOPÉRATIFS – ZEN.ECONOMY UPlanet ẐEN"
echo "══════════════════════════════════════════════════════════════════════"
echo ""
echo "🌍 Banque Centrale Ğ1 (UPLANETNAME_G1)"
echo "   → Réserve de valeur en Ğ1 permettant d'émettre des Ẑen (1Ẑ = 0.1Ğ1)."
echo "   → Alimente tous les flux économiques (MULTIPASS, SOCIETY, etc.)"
echo "   UPLANETNAME_G1=$UPLANETNAME_G1"
echo ""
echo "💸 Portefeuille ẑen (UPLANETG1PUB)"
echo "   → Point d'entrée des jetons d'usage (MULTIPASS)."
echo "   UPLANETG1PUB=$UPLANETG1PUB"
echo ""
echo "🤝 Portefeuille SOCIETY ẐEN / AMAP (UPLANETNAME_SOCIETY)"
echo "   → Reçoit les cotisations des sociétaires (ẐEN)."
echo "   → Redistribue X% R&D, Y% ASSETS, Z% -> ẑen (reste au CAPITAINE)."
echo "   UPLANETNAME_SOCIETY=$UPLANETNAME_SOCIETY"
echo ""
echo "🏭 Immobilisations corporelles – CAPITAL (UPLANETNAME_CAPITAL)"
echo "   → Capital machine (infrastructure)."
echo "   → Amortissement linéaire sur 3 ans (156 semaines)."
echo "   UPLANETNAME_CAPITAL=$UPLANETNAME_CAPITAL"
echo ""
echo "📊 Taxe / TVA – IMPOT (UPLANETNAME_IMPOT)"
echo "   → Collecte les prélèvements fiscaux : x% sur chaque transaction MULTIPASS."
echo "   UPLANETNAME_IMPOT=$UPLANETNAME_IMPOT"
echo ""
echo "💰 Trésorerie – TREASURY (UPLANETNAME_TREASURY)"
echo "   → Fonds de roulement, réserve de liquidités pour conversion ẑ/€."
echo "   UPLANETNAME_TREASURY=$UPLANETNAME_TREASURY"
echo ""
echo "🔬 Recherche & Développement – RnD (UPLANETNAME_RND)"
echo "   → Financement de l'innovation, des outils et de la maintenance"
echo "     du logiciel coopératif. Reçoit X% des cotisations sociétaires."
echo "   UPLANETNAME_RND=$UPLANETNAME_RND"
echo ""
echo "🌱 Actifs environnementaux – ASSETS (UPLANETNAME_ASSETS)"
echo "   → Récompenses ORE (terrains, UMAP)."
echo "   → Réserves pour la régénération écologique et les actions climatiques."
echo "   UPLANETNAME_ASSETS=$UPLANETNAME_ASSETS"
echo ""
echo "🚢 Portefeuille Collecte (UPLANETNAME_CAPTAIN)"
echo "   → Reçoit les revenus de gestion."
echo "   UPLANETNAME_CAPTAIN=$UPLANETNAME_CAPTAIN"
echo ""
echo "🖥️  Armateur Astroport – NODE (UPLANETNAME_NODE)"
echo "   → Revenus locatifs (PAF) et burn vers les monnaies locales (€)."
echo "   → Distinct du capital machine (UPLANETNAME_CAPITAL)."
echo "   UPLANETNAME_NODE=$UPLANETNAME_NODE"
echo ""
echo "🆔 Identifiant du nœud IPFS (IPFSNODEID)"
echo "   → Trace la machine Y Level (SSH=IPFS)."
echo "   IPFSNODEID=$IPFSNODEID"
echo ""
cowsay "$(hostname) on UPLANET ${UPLANETG1PUB:0:8}" 2>/dev/null \
    || echo "⚓ $(hostname) on UPLANET ${UPLANETG1PUB:0:8}"
echo "CAPTAIN: $CAPTAINEMAIL"
