HTTP/1.1 200 OK
Server: Astroport
Content-Type: text/html; charset=UTF-8

<!doctype html>
<html>
  <head>
    <meta http-equiv="refresh" content="5; url='http://127.0.0.1:12345'" />
    <style>
    #wait {
    width:42%;
    height:42%;
    }
    </style>
    <title>[Astroport] IPFS - Basic Input Output Social System - BIOSS - Astronaut TW's -</title>

  </head>
<body>
<center>
<h1>ASTROPORT Ŋ1</h1>
<b>Astronaute... ouverture du sas... S'il a du mal à s'ouvrir: insistez !</b><br>
<img src='http://127.0.0.1:8080/ipfs/QmS4xmYNpto1ce65VBPJsDjiaoupmxTTE7o5RD2zrnJcVb/QRCode.gif' id='wait'/>
</center>
</body>
</html>
