graph LR
    A[Portefeuille UPlanet G1PUB] <--> B{Prélévement Mensuel};
    B <--> C[Portefeuille ♥Box SSH=IPFS];
    B <--> D[Portefeuille Capitaine];
    A <--> F[Portefeuilles PLAYERs Locataires et Obligataires];
        B <-->|Forfait # 1, 2, 4Ẑ # 19Ẑ # 12Ẑ # | F;

    B --> G{REPARTITION};
         G --> H(1/3 vers MIZ);
         G --> I(1/3 vers G1FabLab);
         G --> J(1/3 vers R&D)
   style A fill:#ccf,stroke:#333,stroke-width:2px
    style B fill:#ddd,stroke:#333,stroke-width:2px
    style C fill:#eef,stroke:#333,stroke-width:2px
    style D fill:#fcc,stroke:#333,stroke-width:2px
	 style F fill:#ffe,stroke:#333,stroke-width:2px
    style G fill:#ddf,stroke:#333,stroke-width:2px
      style H fill:#ddd,stroke:#333,stroke-width:2px
     style I fill:#ddd,stroke:#333,stroke-width:2px
	  style J fill:#ddd,stroke:#333,stroke-width:2px