HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
Access-Control-Allow-Methods: GET
Server: Astroport.ONE
Content-Type: text/html; charset=UTF-8

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>[Astroport] :: Station _HOSTNAME_ :: _IPFSNODEID_ </title>
    <meta http-equiv="refresh" content="9999; url='http://127.0.0.1:12345'" />
    <link rel="icon" type="image/png" href="http://127.0.0.1:8080/ipfs/QmaCh8mywWfxkXF3JziFzqZS6yZFo3eNS5fSfnzJqdSQvX/logo.png" />
    <link rel="stylesheet" href="http://127.0.0.1:8080/ipfs/QmaCh8mywWfxkXF3JziFzqZS6yZFo3eNS5fSfnzJqdSQvX/decoration.css" type="text/css" />
    <link rel="stylesheet" href="http://127.0.0.1:8080/ipfs/QmaCh8mywWfxkXF3JziFzqZS6yZFo3eNS5fSfnzJqdSQvX/layout.css" type="text/css" />
    <style>

body {
    background-image:url("http://127.0.0.1:8080/ipfs/QmSFgatcq3q898J56epa8SyGbH651vRBFnv93kQSwfoi83/background.000.jpg");
    background-repeat: no-repeat;
    background-size: 100% 100%;
}
html {
    height: 100%
}
header {
    opacity: 0.8;
}
    input[type=submit] {
    width: 12em;  height: 4em;
    }
    input[type=checkbox] {
    width: 2em;  height: 2em;
    }
    input {
    width: 26em;  height: 2em;
    }
#yellow {
      background: yellow;
      position: absolute;
      top: 12%;
      left: 66%;
      width: 18%;
      visibility: hidden;
    }
#login {
    right: 10%;
    top: 5%
 }
    </style>
    <!-- Typed text animation -->
    <script src="http://127.0.0.1:8080/ipfs/QmYyJmAT3cUbjk4vVWQG7LdpY3HkFH9phFD1VzzetHrgpa"></script>
    <!-- Astro API JS LIB -->
    <script src="http://127.0.0.1:8080/ipfs/Qmae5v9zydax9u6C9ceDijURu5PYdd5avmv4NkenCw7RFv/astro.js"></script>

</head>
<body>
<header>

<!--
            <div  id="login"><button onclick="promptUser('login')">LOGIN</button><button onclick="promptUser('logout')">LOGOUT</button></div>
-->
    <h6>
        <p id="station"> ♥<span>BOX <div id='countdown'></div></span></p>
   </h6>
        <span><div id="ainfo"></div></span>
        <div id="debug"></div>

</header>

<main>

<center>
<b>Welkom - Mirë se vini -  Willkommen - Welkomma - Welcome - Marhaban - Bari galoust - Xos gelmissiniz - Welkum -  Ongi etorri- Swagata - Ansuf yiswen - ščyra zaprašajem - Kyo tzo pa eit - ॐ★ॐ - Ani kié - Dobro došli - Dagemer mat - Dobre doshŭl - Benvinguts - Ulihebisdi - ௐ- Huān yíng - Karibu - Eoso eoseyo - Benvenuti - Bel bonjou - Bienvini - Dobrodošli - Velkommen - Bienvenido -  Bonvenon - Tere tulemast - Gabitê - Vælkomin -  Tervetuloa - Welkom - Wìllkòmme - Binvignut - Fàilte - Benvido - Croeso - Planvenguda - Mikouabô - Kalos irthate - Eguahé porá - Baroukh habaim - ﷽ </b><br>
<header>

         <div>
        <button onclick="homeAstroportStation('http://127.0.0.1:12345/?qrcode=station', '', 21654)">Ğ1Station</button>
        </div>
<form id="formlink" action = "http://127.0.0.1:1234" method = "GET" enctype="application/x-www-form-urlencoded">
    <h1><span>Astroport</span> <a href="http://127.0.0.1:12345">Ŋ1</a></h1>
    <div id="yellow">
        <h2>G1Card SECRETS</h2>
        <input name='salt' value='0'>
<h3><a title="YOUR ASTRO PORT" href="http://127.0.0.1:12345"> >>> (◕‿‿◕) <<< </a></h3>
        <input name='pepper' value='0'>
</div>
        <h2>
        <div id="typed-strings">
            <p><span>/ <strong><em><a href="https://opencollective.com/monnaie-libre/projects/coeurbox" target="funding">La♥BOX</a></em></strong> /</span>^3223</p>
            <p>&#8984; Interplanetary <em>Cloud Storage</em> &#9925;</span> ^3222</p>
            <p>We Make <strong><em><u>👉<a href="https://opencollective.com/monnaie-libre">Le Claude</a>👈</u></em></strong>^3112</p>
            <p>🔥.^999.^888.^777.^666.^555.^444.3^333.2^222.1^111 🚀^4321</p>
        </div>
        <span id="typed"></span>
        </h2>
        <span><a target="youtube" href="https://youtube.com">📺 (&#128077;)</a> : </span><input name=g1pub value='enter video source to feed in TW'></br>
        <span>Email : </span><input name=email value=''></br></br>
        <input type='submit' value='[(♥‿‿♥)]'>

</form>

</h2>
</br>
            <p>
            <b><a target="pad" href="https://vdo.copylaradio.com/?room=cocoding">COCODING CHAT ROOM</a></b>
            </p>
</header>

</center>

<article>
    <div class="row justify-center">
        <h1 class="video-title">
            <center>
                <a href="https://astroport.com">Astroport.ONE</a>
                <a href="https://opencollective.com/monnaie-libre/projects/coeurbox" target="funding">- ♥BOX Edition - </a>
                <a href="https://olympe.network">Olympe.Network</a><br>
                Astroport.ONE est un logiciel libre développé sous licence AGPL v3
        </center>
            <a target="gchange" href="https://gchange.fr">Une fois votre G1CARD obtenu, direction https://gchange.fr !</a>
        </h1>
    </div>
</article>
<article>
    <div class="row justify-center">
        <ul>
            <li>Installez Astroport.ONE puis ajoutez <a href="http://127.0.0.1:8080/ipns/docs.ipfs.tech/install/ipfs-companion/" target="doc"><b>ipfs-companion</b></a> à votre navigateur </li>
        </ul>
    </div>
</article>
BECOME ASTROŊAUTE
explore
Astroport Ŋ1 Swarm#0

Associate your key phrases with an email address

Phrase One ("login")
Phrase Two ("password")

Accept delegation of your key (Ŋ1 20h12 bitswap)

Need help? Contact support@qo-op.com
Astroport operates a 100% blockchain digitalization.
Copy, store, share, broadcast your multimedia and json channels in IPFS, between friends!
Take possession of your TW. Make freedom of expression uncensurable, unstoppable.
<br/><center><a href="https://git.p2p.legal/qo-op/Astroport.ONE">
>>> Let's reboot the INTERNET - Install IPFS - Activate Astroport.ONE <<<
</a></center><br/>
<center>
    <h6>
        <a href="https://madeinzion.org">Made In Zion funded project _\/_ </a> powered by <a href="https://astroport.com"><span>"</span>Astroport<span>"</span></a>
    </h6>
</center>
</main>
</body>

<script>
  var typed = new Typed('#typed', {
    stringsElement: '#typed-strings',
    smartBackspace: true,
    backDelay: 700,
    loop: true,
    typeSpeed: 40
  });
</script>

<script>
const el = document.getElementById('yellow');
//~ const log = document.getElementById('login');
//~ log.style.visibility = 'visible';

setTimeout(() => {
    el.style.visibility = 'visible';
}, 3456); // 👈️ delay in milliseconds

var arrTimes = [];
var i = 0; // start
var timesToTest = 3;
var tThreshold = 300; //ms
var testImage = "https://ipfs.copylaradio.com/ipfs/QmUUyiuCM4yXgaeGyqC2SVUUXZksuxhDfHQYpUpZPuL2oS/astroport.jpg"; // small image in your server
var dummyImage = new Image();
var isConnectedFast = false;

testLatency(function(avg){
  isConnectedFast = (avg <= tThreshold);
  /** output */
  document.body.appendChild(
    document.createTextNode("Time: " + (avg.toFixed(2)) + "ms - ♥Box ready ? " + isConnectedFast)
  );
});

/** test and average time took to download image from server, called recursively timesToTest times */
function testLatency(cb) {
  var tStart = new Date().getTime();
  if (i<timesToTest-1) {
    dummyImage.src = testImage + '?t=' + tStart;
    dummyImage.onload = function() {
      var tEnd = new Date().getTime();
      var tTimeTook = tEnd-tStart;
      arrTimes[i] = tTimeTook;
      testLatency(cb);
      i++;
    };
  } else {
    /** calculate average of array items then callback */
    var sum = arrTimes.reduce(function(a, b) { return a + b; });
    var avg = sum / arrTimes.length;
    cb(avg);
  }
}

</script>
<script>

    let cookies = document.cookie;
    console.log(cookies);

    var timeLeft = 5;
    var elem = document.getElementById("countdown");
    var timerId = setInterval(countdown, 999);

    function countdown() {
        if (timeLeft == -1) {
            clearTimeout(timerId);
            document.getElementById("countdown").innerHTML = "<form method='get' action='http://g1billet.localhost:33101' target='aframe'><input type='hidden' name='montant' value='0' ><label for='type'>Type :</label><select name='type'><option value=''>G1BILLET+ ( x 6 )</option><option value='jeu'>G1CARD</option><option value='@astroport'>G1CARD+@</option></select><input type='hidden' name='dice' value='4' >&nbsp;&nbsp;&nbsp;&nbsp;<button type='submit'>Lancer Fabrication</button></form>";
        } else {
            // elem.innerHTML = timeLeft + " s";
            timeLeft--;
        }
    }
    // promptUser();
</script>

</html>
