services:

  peertube:
    image: chocobozzz/peertube:v6.0.2-bookworm
    container_name: peertube
    env_file:
      - .env
    ports:
      - "1935:1935"  # Comment if you don't want to use the live feature
      - "9000:9000" # Uncomment if you use another webserver/proxy or test PeerTube in local, otherwise not suitable for production
    volumes:
      - ./data:/data
      - ./config:/config
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    restart: "always"
    networks:
      - peertube

  postgres:
    image: postgres:13-alpine
    container_name: peertube_postgres
    env_file:
      - .env
    volumes:
      - ./postgres:/var/lib/postgresql/data
    restart: "always"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - peertube

  redis:
    image: redis:6-alpine
    container_name: peertube_redis
    volumes:
      - ./redis:/data
    restart: "always"
    networks:
      - peertube

networks:
  peertube:
    name: peertube

