version: '3.8'

services:
  nextcloud-aio-mastercontainer:
    image: nextcloud/all-in-one:latest
    container_name: nextcloud-aio-mastercontainer
    restart: always
    init: true
    ports:
      - "8008:80"
      - "8002:8080"
      - "8443:8443"
    environment:
      - SKIP_DOMAIN_VALIDATION=true
      - APACHE_PORT=8001
      - APACHE_IP_BINDING=0.0.0.0
      - NEXTCLOUD_DATADIR=/nextcloud-data
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    dns:
      - 8.8.8.8
      - 1.1.1.1

volumes:
  nextcloud_aio_mastercontainer:
